# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookBori' do
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire', '~> 5.5'
  pod 'IQKeyboardManager' #iOS8 and later

end
